# Generated by Django 3.0.2 on 2020-02-03 12:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('src', models.CharField(default='https://studysmartbucket.s3.amazonaws.com/media/', max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('src', models.CharField(default='https://studysmartbucket.s3.amazonaws.com/media/', max_length=120)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=60)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagesrc', models.CharField(max_length=120)),
                ('sellername', models.CharField(max_length=20)),
                ('contact', models.BigIntegerField()),
                ('isapproved', models.BooleanField(default=False)),
                ('uploaded_file', models.FileField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='subject_names',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='User_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_input', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='download',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('url', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('books and notes', 'books and notes'), ('paper', 'paper')], default='books and notes', max_length=80)),
                ('uploaded_file', models.FileField(default='test', upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.subject_names')),
            ],
        ),
    ]
