# Generated by Django 3.0.2 on 2020-01-11 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='subject',
            new_name='download',
        ),
    ]
