# Generated by Django 3.0.2 on 2020-02-08 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
