# Generated by Django 3.0.2 on 2020-02-12 21:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20200208_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download',
            name='uploaded_file',
            field=models.FileField(default='test', upload_to='pdf', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'zip'])]),
        ),
    ]
