# Generated by Django 3.0.2 on 2020-02-12 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20200213_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='uploaded_file',
            field=models.FileField(upload_to='images'),
        ),
    ]
