# Generated by Django 3.0.2 on 2020-02-15 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20200213_0256'),
    ]

    operations = [
        migrations.AddField(
            model_name='download',
            name='haspaper',
            field=models.BooleanField(default=True),
        ),
    ]
