# Generated by Django 3.0.2 on 2020-01-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20200112_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='contact',
            field=models.BigIntegerField(),
        ),
    ]
