# Generated by Django 3.0.2 on 2020-01-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20200112_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject_names',
            name='driveid',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
    ]
