# Generated by Django 3.0.2 on 2020-02-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20200216_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='src',
            field=models.CharField(default='#', max_length=120),
        ),
    ]
