# Generated by Django 3.0.2 on 2020-02-16 12:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20200216_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='uploaded_file',
            field=models.FileField(default='test', upload_to='notice', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AddField(
            model_name='notice',
            name='uploaded_file',
            field=models.FileField(default='test', upload_to='notice', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
