# Generated by Django 3.0.2 on 2020-01-19 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20200119_1715'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
