# Generated by Django 3.0.2 on 2020-01-19 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_delete_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='contact',
            field=models.BigIntegerField(),
        ),
    ]
