# Generated by Django 3.0.2 on 2020-01-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20200119_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isapproved',
            field=models.BooleanField(default=False),
        ),
    ]
