# Generated by Django 3.0.2 on 2020-01-26 11:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_product_isapproved'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='uploaded_file',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
