# Generated by Django 3.0.2 on 2020-01-26 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_product_uploaded_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
