# Generated by Django 3.0.2 on 2020-01-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=60)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagesrc', models.URLField()),
                ('sellername', models.CharField(max_length=20)),
                ('contact', models.BigIntegerField()),
                ('isapproved', models.BooleanField(default=False)),
                ('uploaded_file', models.FileField(upload_to='')),
            ],
        ),
    ]
