# Generated by Django 3.0.2 on 2020-01-30 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_auto_20200128_0234'),
    ]

    operations = [
        migrations.AddField(
            model_name='download',
            name='uploaded_file',
            field=models.FileField(default='test', upload_to=''),
        ),
    ]
