# Generated by Django 3.0.2 on 2020-01-30 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_download_uploaded_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download',
            name='url',
            field=models.CharField(max_length=120),
        ),
    ]
