# Generated by Django 3.0.2 on 2020-01-31 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_auto_20200131_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='src',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='notice',
            name='src',
            field=models.CharField(max_length=120),
        ),
    ]
