# Generated by Django 3.0.2 on 2020-01-31 19:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_auto_20200131_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download',
            name='uploaded_file',
            field=models.FileField(default='test', upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
