# Generated by Django 3.0.2 on 2020-02-01 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_auto_20200201_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='uploaded_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
