# Generated by Django 3.0.2 on 2020-02-01 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_auto_20200201_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject_names',
            name='driveid',
        ),
    ]
