# Generated by Django 3.0.2 on 2020-02-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_remove_subject_names_driveid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='src',
            field=models.CharField(default='https://studysmartbucket.s3.amazonaws.com/media/', max_length=120),
        ),
        migrations.AlterField(
            model_name='notice',
            name='src',
            field=models.CharField(default='https://studysmartbucket.s3.amazonaws.com/media/', max_length=120),
        ),
    ]
